### ISSUE TITLE
Getting the following error on install

### ISSUE THREAD

**Issue by amulyaparmar** [ActivityWatch/docs#10]
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: initfsencoding: unable to load the file system codec
zipimport.ZipImportError: can't find module 'encodings'

**Comment by amulyaparmar** [comment]
never tried installing something via the ./aw-qt before. Would highly appreciate if there could be some better guidance here.

**Comment by ErikBjare** [comment]
What operating system are you using?

**Comment by johan-bjareholt** [comment]
No response, closing
