### ISSUE TITLE
Missing Fetchinng Data documentation

### ISSUE THREAD

**Issue by laszukdawid** [ActivityWatch/docs#23]
Hi guys,

First of all, kudos for great work! Thanks so much for this project and writing docs. Documentation isn't the sexiest thing but it's THE thing that makes the whole product sexy.

Seems that some links are empty, e.g. all Fetching Data links in [Extending ActivityWatch](https://activitywatch.readthedocs.io/en/latest/extending.html). I can see that there are some docs ([querying-data.rst](https://github.com/ActivityWatch/docs/blob/e7b8feb2d12008f20bd2f04eae2e3e807805d378/querying-data.rst)) that are related. Are these links invalid, or the docs are missing?

**Comment by ErikBjare** [comment]
Oops, looks like some of the links are broken! Should be an easy fix, will try to remember it tomorrow.

**Comment by johan-bjareholt** [comment]
I just fixed this in https://github.com/ActivityWatch/docs/commit/794fbae4b06a17d141a2e33d2cf238b399cd5107
