### ISSUE TITLE
Missing a section on updating

### ISSUE THREAD

**Issue by NicoWeio** [ActivityWatch/docs#39]
I was unable to find information on how to update ActivityWatch. At least for Linux users like me, there should be some documentation, answering at least the following questions:

- Can I simply overwrite the old application folder with the contents of a new release _.zip_ file?
- Is my database safe? (I don't even know where it is located)
- Should I kill ActivityWatch before the update? How do I do that?
- Do I have to restart the system?

I don't know the answer to most of these questions. I once installed ActivityWatch and use it happily, but now that it's time to upgrade (which the UI doesn't indicate, by the way), I hardly know what to do.

**Comment by johan-bjareholt** [comment]
That's a good point, I think you are the third person asking this now.

Should definitely be added to the docs!

**Comment by ErikBjare** [comment]
One of the reasons it isn't very well documented is that not a lot can go wrong, you can just remove your old installation and install the new one.

On Windows you can just download a new version of the installer and run that, on Arch Linux you can use the AUR package, on macOS you can update with brew or by simply downloading the new app bundle. 

The data is stored in `~/.local/share/activitywatch` on Linux.

But yes, documentation is needed.

**Comment by NicoWeio** [comment]
For reference: This was added in #225. 

Where would you put the section on _Updating_? How about the _Getting Started_ chapter, right after _Installation_? 

I'd come up with a PR, then.

**Comment by ErikBjare** [comment]
@NicoWeio A section in the docs would be nice! 

I'm trying to keep the *Getting Started* chapter as short as possible, but I think it might be the most appropriate place for now (since it'll probably be a pretty short section anyway). I'd put it after the *Autostart* section though (since it's the last thing the user needs to know).

**Comment by ErikBjare** [comment]
I added this a couple weeks back, along with an uninstall section.
