### ISSUE TITLE
Translate docs : good idea or not ?

### ISSUE THREAD

**Issue by papilip** [ActivityWatch/docs#43]
Hello all,

Is it a good idea to offer a translation of your web pages / docs / interfaces?
If YES, where can I offer it?

Have a nice day, 
Papilip

**Comment by johan-bjareholt** [comment]
It is a good idea, definitely!

For the docs it should not be too hard to implement, but then it would also be good to get the web-ui translated which would be a significant amount of work.

To get you voice heard, please vote on this feature request on the forum! Maybe also add a comment there on what languages you would like to help with translating once that's possible. 
https://forum.activitywatch.net/t/translation-to-other-languages/569

**Comment by papilip** [comment]
@johan-bjareholt 
Thank you for your reply.
I will see how to translate the documentation first.
Then, when the possibility of translating the web interface becomes available, I will start this work.
