### ISSUE TITLE
CI build is failing

### ISSUE THREAD

**Issue by johan-bjareholt** [ActivityWatch/docs#57]
Probably something related to https://github.com/ActivityWatch/aw-server/commit/c004aa972db92989358851ee8154bca24402ad6c

```
  Because aw-server (0.10 git rev master) depends on flask-restx (^0.2.0) which doesn't match any versions, aw-server is forbidden.
  So, because aw-docs depends on aw-server (0.10 git rev master), version solving failed.
```

https://github.com/ActivityWatch/docs/runs/1648852953

**Comment by ErikBjare** [comment]
Pretty sure it just needs a `poetry update`

**Comment by johan-bjareholt** [comment]
Good point, fixed
https://github.com/ActivityWatch/docs/commit/07e9593c52a4ef247c4217c746626c36b9e8f52c
