### ISSUE TITLE
Config file location clarification

### ISSUE THREAD

**Issue by RichardJActon** [ActivityWatch/docs#78]
Thanks for ActivityWatch - it's an Awesome tool!

I wanted to change the afk timeout and looked it up in the docs:
https://docs.activitywatch.net/en/latest/configuration.html?highlight=timeout#configuration

It says I need to make/edit a .toml file with `timeout` value in seconds set but i'm a little unclear on where this should live in the directory structure as it does not quite match with the docs and there are not any existing .toml files in there to go by.

my ~/.local/share/activitywatch has the following structure:

├── aw-client
│   └── queued
│       ├── aw-watcher-afk.v1.persistqueue
│       │   ├── data.db
│       │   ├── data.db-shm
│       │   └── data.db-wal
│       └── aw-watcher-window.v1.persistqueue
│           └── data.db
└── aw-server
    ├── device_id
    └── peewee-sqlite.v2.db

could you help me out with this?

**Comment by ErikBjare** [comment]
You're looking in the wrong directory. Check in
https://docs.activitywatch.net/en/latest/directories.html#config-directory

**Comment by RichardJActon** [comment]
ah yep .config for the config that adds up - thanks for helping me notice the obvious.
